local feminine_seasons =
{
  veryshortseason = STRINGS.ES_TRANSLATION.UI.SANDBOXMENU.FEMININEVERYSHORT,
  shortseason = STRINGS.ES_TRANSLATION.UI.SANDBOXMENU.FEMININESHORT,
  default = STRINGS.ES_TRANSLATION.UI.SANDBOXMENU.FEMININEDEFAULT,
  longseason = STRINGS.ES_TRANSLATION.UI.SANDBOXMENU.FEMININELONG,
  verylongseason = STRINGS.ES_TRANSLATION.UI.SANDBOXMENU.FEMININEVERYLONG
}

customise_mod =
{
  day =
  {
    options =
    {
      onlyday = capitalizeFirstLetter,
      onlydusk = capitalizeFirstLetter,
      onlynight = capitalizeFirstLetter,
      longday = capitalizeFirstLetter(STRINGS.UI.SANDBOXMENU.DAY .. " " .. STRINGS.UI.SANDBOXMENU.SLIDELONG),
      longdusk = capitalizeFirstLetter(STRINGS.UI.SANDBOXMENU.DUSK .. " " .. STRINGS.UI.SANDBOXMENU.SLIDELONG),
      longnight = capitalizeFirstLetter(STRINGS.UI.SANDBOXMENU.NIGHT .. " " .. STRINGS.ES_TRANSLATION.UI.SANDBOXMENU.FEMININELONG),
      noday = capitalizeFirstLetter(STRINGS.ES_TRANSLATION.UI.SANDBOXMENU.WITHOUT .. " " .. STRINGS.UI.SANDBOXMENU.DAY),
      nodusk = capitalizeFirstLetter(STRINGS.ES_TRANSLATION.UI.SANDBOXMENU.WITHOUT .. " " .. STRINGS.UI.SANDBOXMENU.DUSK),
      nonight = capitalizeFirstLetter(STRINGS.ES_TRANSLATION.UI.SANDBOXMENU.WITHOUT .. " " .. STRINGS.UI.SANDBOXMENU.NIGHT)
    }
  },

  season =
  {
    options =
    {
      onlysummer = capitalizeFirstLetter,
      onlywinter = capitalizeFirstLetter,
      longsummer = capitalizeFirstLetter(STRINGS.UI.SANDBOXMENU.SUMMER .. " " .. STRINGS.UI.SANDBOXMENU.SLIDELONG),
      longwinter = capitalizeFirstLetter(STRINGS.UI.SANDBOXMENU.WINTER .. " " .. STRINGS.UI.SANDBOXMENU.SLIDELONG),
      longboth = STRINGS.UI.SANDBOXMENU.BOTH .. " " .. STRINGS.ES_TRANSLATION.UI.SANDBOXMENU.LONGPLURAL,
      shortboth = STRINGS.UI.SANDBOXMENU.BOTH .. " " .. STRINGS.ES_TRANSLATION.UI.SANDBOXMENU.SHORTPLURAL
    }
  },

  dry = { options = feminine_seasons },
  humid = { options = feminine_seasons },
  hurricane = { options = feminine_seasons },
  lush = { options = feminine_seasons },
  mild = { options = feminine_seasons },
  monsoon = { options = feminine_seasons },
  spring = { options = feminine_seasons },
  temperate = { options = feminine_seasons },

  beefaloheat =
  {
    options =
    {
      rare = "Baja",
      default = "Media",
      often = "Alta",
      always = "Muy alta"
    }
  },

  adult_flytraps = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.ADULTFLYTRAPS },
  ballphins = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.BALLPHINS },
  bamboo = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.BAMBOO },
  bats = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.BATS },
  bearger = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.BEARGERS },
  beefalo = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.BEEFALOS },
  berrybush = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.BERRYBUSHES },
  bioluminescence = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.BIOLUMINESCENCE },
  braincoral = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.BRAINCORAL },
  butterfly = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.BUTTERFLIES },
  buzzard = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.BUZZARDS },
  carrot = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.CARROTS },
  catcoon = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.CATCOONS },
  claw_trees = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.CLAWPALMTREES },
  coral = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.CORAL },
  crabbits = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.CRABHOLES },
  crates = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.CRATES },
  crocodog = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.CROCODOGS },
  crumbling_brazier = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.BRAZIERS },
  deerclops = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.DEERCLOPS },
  dogfish = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.DOGFISH },
  dragonfly = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.DRAGONFLIES },
  dragooneggs = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.DRAGOONEGGS },
  dung_beetles = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.DUNGBEETLES },
  dung_piles = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.DUNGPILES },
  flint = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.FLINTS },
  flipping_rocks = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.FLIPPINGROCKS },
  flups = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.FLUPS },
  giant_grubs = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.GIANTGRUBS },
  glowflies = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.GLOWFLIES },
  gnat = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.GNATSWARMS },
  gnat_mounds = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.GNATMOUNDS },
  grabbing_vines = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.GRABBINGVINES },
  grass = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.GRASS },
  guard_towers = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.GUARDTOWERS },
  hanging_vines = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.HANGINGVINES },
  hippopotamoose = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.HIPPOPOTAMOOSE },
  houndmound = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.HOUNDMOUNDS },
  iceboulder = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.ICEBOULDERS },
  jellyfish = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.JELLYFISH },
  kraken = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.KRAKEN },
  lamp_posts = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.LAMPPOSTS },
  lightning_goat = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.LIGHTNINGGOATS },
  lily_pads = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.LILYPADS },
  limpets = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.LIMPETROCKS },
  lobsters = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.LOBSTERS },
  lotus = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.LOTUS },
  mandrake = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.MANDRAKES },
  mandrake_men = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.MANDRAKEMEN },
  mant_comb_homes = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.ANTCOMBHOME },
  mant_lamps = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.MANTLAMPS },
  mean_flytraps = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.MEANFLYTRAPS },
  merms = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.MERMS },
  monkeys = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.MONKEYS },
  mosquitos = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.MOSQUITOS },
  nettle = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.NETTLES },
  orange_pikos = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.PIKOS },
  ox = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.OXEN },
  palmguard = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.PALMGUARDS },
  pangolden = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.PANGOLDENS },
  peagawk = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.PEAGAWKS },
  perd = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.PERDS },
  pig_bandit = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.PIGBANDITS },
  pig_ghosts = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.PIGGHOSTS },
  pig_houses = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.PIGHOUSES },
  platypine = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.BILLS },
  pogs = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.POGS },
  poison_dart_frogs = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.POISONFROGS },
  poisonhole = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.POISONHOLES },
  radish = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.RADISHES },
  rainforest_trees = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.RAINFORESTTREES },
  sand = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.SANDHILLS },
  sapling = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.SAPLINGS },
  scorpions = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.SCORPIONS },
  seagulls = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.SEAGULLS },
  seashell = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.SEASHELLS },
  shoals = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.SHOALS },
  small_ruins = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.RUINSENTRANCE },
  snakes = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.SNAKES },
  stinkrays = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.STINKRAYS },
  sweetpotatos = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.SWEETPOTATOS },
  swordfish = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.SWORDFISH },
  tall_grass = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.TALLGRASS },
  tea_trees = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.TEATREES },
  thunderbirds = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.THUNDERBIRDS },
  tidalpools = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.TIDALPOOLS },
  tigershark = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.TIGERSHARKS },
  tuber_trees = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.TUBERTREES },
  tumbleweeds = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.TUMBLEWEEDS },
  twister = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.SEALNADOS },
  vampire_bat_caves = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.CAVECLEFTS },
  vampire_bats = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.VAMPIREBATS },
  vines = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.VINES },
  warg = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.WARGS },
  weevole = { tooltip = STRINGS.ES_TRANSLATION.UI.CUSTOMIZATIONSCREEN.NAMES.WEEVOLES }
}

return customise_mod
