-- Shipwrecked wildbores. / Cerdos salvajes de Shipwrecked.
STRINGS.BORE_TALK_FOLLOWWILSON[2] = "AMAR AMIGA"
STRINGS.BORE_TALK_FOLLOWWILSON[3] = "TÚ BUENA"
STRINGS.BORE_TALK_LOOKATWILSON[3] = "FEA MUJER MONO"

-- Hamlet city pigs. / Cerdos de ciudad de Hamlet.
STRINGS.CITY_PIG_GUARD_TALK_ANGRY_PLAYER.DEFAULT[2] = "¡BELLACA! ¡RUIN!"
STRINGS.CITY_PIG_GUARD_TALK_FIGHT.DEFAULT[3] = "¡LARGO, BELLACA! ¡LARGO!"
STRINGS.CITY_PIG_GUARD_TALK_LOOKATWILSON.DEFAULT[3] = "¡NO FORASTERAS!"
STRINGS.CITY_PIG_SHOPKEEPER_NOT_ENOUGH[1] = "ESCASA DE OINCS ESTÁ"
STRINGS.CITY_PIG_SHOPKEEPER_ROBBED[2] = "¡LADRONA! ¡LADRONA! ¡LADRONA!"
STRINGS.CITY_PIG_SHOPKEEPER_ROBBED[3] = "¡QUÉ CERDA!"
STRINGS.CITY_PIG_TALK_APORKALYPSE_REWARD.DEFAULT[3] = "¡BUENA USTED ES!"
STRINGS.CITY_PIG_TALK_FIGHT.pigman_banker[1] = "¡MI AMIGA NO ERES!"
STRINGS.CITY_PIG_TALK_FIGHT.pigman_collector[3] = "¡NO-CERDO MALA!"
STRINGS.CITY_PIG_TALK_FIGHT.pigman_erudite[1] = "¡NO-CERDO MALVADA! ¡MALA!"
STRINGS.CITY_PIG_TALK_FIGHT.pigman_florist[3] = "¡UNA VILLANA ERES!"
STRINGS.CITY_PIG_TALK_FIGHT.pigman_hunter[3] = "¡BIENVENIDA NO ERES!"
STRINGS.CITY_PIG_TALK_FIGHT.pigman_professor[3] = "¡LARGO, NO-CERDO MALDITA!"
STRINGS.CITY_PIG_TALK_FIGHT.pigman_storeowner[2] = "¡AQUÍ NO LA QUIERO!"
STRINGS.CITY_PIG_TALK_POOPTIP.pigman_erudite[2] = "COMO UNA PROFESIONAL RECOGE POPÓ"
STRINGS.CITY_PIG_TALK_POOPTIP.pigman_hatmaker[1] = "A LA NO-CERDO PAGO COMO SE DEBE"
STRINGS.CITY_PIG_TALK_POOPTIP.pigman_hatmaker[2] = "LA NO-CERDO QUÉ TRABAJADORA ES"
STRINGS.CITY_PIG_TALK_POOPTIP.pigman_mechanic[2] = "¿PAGO JUSTO, NO-CERDO JUSTA?"
STRINGS.CITY_PIG_TALK_POOPTIP.pigman_shopkeep[1] = "UNA HONORABLE NO-CERDO ES"

-- Elder mandrake. / Mandrágora mayor.
STRINGS.MANDRAKEMAN_MANDRAKE_BATTLECRY[1] = "¡LADRONA!"
STRINGS.MANDRAKEMAN_MANDRAKE_BATTLECRY[2] = "¡BANDIDA!"

-- Pig mans. / Hombres cerdo.
STRINGS.PIG_TALK_FOLLOWWILSON[1] = "TÚ AMIGA"
STRINGS.PIG_TALK_FOLLOWWILSON[2] = "AMAR AMIGA"
STRINGS.PIG_TALK_FOLLOWWILSON[3] = "TÚ BUENA"
STRINGS.PIG_TALK_LOOKATWILSON[3] = "FEA MUJER MONO"

-- Bunnymans. / Hombres conejo.
STRINGS.RABBIT_MEAT_BATTLECRY[2] = "¡SUCIA!"
STRINGS.RABBIT_MEAT_BATTLECRY[3] = "¡ASESINA!"

-- Sunken boat. / Barca hundida. (Wolly)
STRINGS.SUNKEN_BOAT_REFUSE_TRADE[4] = "¡Marinera de agua dulce!"

-- Pirate parrot. / Loro pirata.
STRINGS.TALKINGBIRD.on_ground[3] = "¡Cabezona!"
STRINGS.TALKINGBIRD.on_mounted[3] = "¿Estás segura?"

AddSimPostInit(function(player)
  if player.prefab == "wilba" then
    STRINGS.BORE_TALK_LOOKATWILSON[3] = "FEA MUJER CERDO"
    
    STRINGS.CITY_PIG_GUARD_TALK_LOOKATWILSON.DEFAULT[3] = "¡NO HAGA NADA MALO!"
    STRINGS.CITY_PIG_TALK_FIGHT.pigman_collector[3] = "¡CERDA MALA!"
    STRINGS.CITY_PIG_TALK_FIGHT.pigman_erudite[1] = "¡CERDA MALVADA! ¡MALA!"
    STRINGS.CITY_PIG_TALK_FIGHT.pigman_professor[3] = "¡LARGO, CERDA MALDITA!"
    STRINGS.CITY_PIG_TALK_POOPTIP.pigman_hatmaker[1] = "A LA CERDITA PAGO COMO SE DEBE"
    STRINGS.CITY_PIG_TALK_POOPTIP.pigman_hatmaker[2] = "UNA CERDITA TRABAJADORA USTED ES"
    STRINGS.CITY_PIG_TALK_POOPTIP.pigman_shopkeep[1] = "UNA HONORABLE CERDITA ES"
    
    STRINGS.PIG_TALK_LOOKATWILSON[3] = "FEA MUJER CERDO"
  end
end)
