--[[
  WX-78
  Webber
  Wilbur
  Wormwood
]]

-- Shipwrecked Wildbores. / Cerdos salvajes de Shipwrecked.
STRINGS.BORE_TALK_FOLLOWWILSON[2] = "YO AMARTE"
STRINGS.BORE_TALK_FOLLOWWILSON[3] = "TÚ AMABLE"
STRINGS.BORE_TALK_LOOKATWILSON[3] = "FEA COSA NO CERDO"

-- Hamlet city pigs. / Cerdos de ciudad de Hamlet.
STRINGS.CITY_PIG_GUARD_TALK_ANGRY_PLAYER.DEFAULT[2] = "¡INFAME! ¡RUIN!"
STRINGS.CITY_PIG_GUARD_TALK_FIGHT.DEFAULT[3] = "¡LARGO, INFAME! ¡LARGO!"
STRINGS.CITY_PIG_GUARD_TALK_LOOKATWILSON.DEFAULT[3] = "¡NO TURISTAS!"
STRINGS.CITY_PIG_SHOPKEEPER_NOT_ENOUGH[1] = "CARENTE DE OINCS ESTÁ"
STRINGS.CITY_PIG_SHOPKEEPER_ROBBED[2] = "¡ME HAN ROBADO! ¡ME HAN ROBADO!"
STRINGS.CITY_PIG_SHOPKEEPER_ROBBED[3] = "¡DESPRECIABLE!"
STRINGS.CITY_PIG_TALK_APORKALYPSE_REWARD.DEFAULT[3] = "¡ALGUIEN AMABLE USTED ES!"
STRINGS.CITY_PIG_TALK_FIGHT.pigman_banker[1] = "¡AGRADABLE NO ERES!"
STRINGS.CITY_PIG_TALK_FIGHT.pigman_collector[3] = "¡NO-CERDO VIL!"
STRINGS.CITY_PIG_TALK_FIGHT.pigman_erudite[1] = "¡NO-CERDO CRUEL! ¡VIL!"
STRINGS.CITY_PIG_TALK_FIGHT.pigman_florist[3] = "¡EXECRABLE USTED ES!"
STRINGS.CITY_PIG_TALK_FIGHT.pigman_hunter[3] = "¡IRSE USTED DEBERÍA!"
STRINGS.CITY_PIG_TALK_FIGHT.pigman_professor[3] = "¡LARGO, NO-CERDO DESPRECIABLE!"
STRINGS.CITY_PIG_TALK_FIGHT.pigman_storeowner[2] = "¡AQUÍ NO LE QUIERO!"
STRINGS.CITY_PIG_TALK_POOPTIP.pigman_erudite[2] = "RECOGIENDO POPÓ EXCELENTE USTED ES"
STRINGS.CITY_PIG_TALK_POOPTIP.pigman_hatmaker[1] = "COMO SE DEBE LE PAGO"
STRINGS.CITY_PIG_TALK_POOPTIP.pigman_hatmaker[2] = "QUÉ SERVICIAL USTED ES"
STRINGS.CITY_PIG_TALK_POOPTIP.pigman_mechanic[2] = "¿PAGO JUSTO, LABOR JUSTA?"
STRINGS.CITY_PIG_TALK_POOPTIP.pigman_shopkeep[1] = "UN SERVICIAL NO-CERDO USTED ES"

-- Elder mandrake. / Mandrágora mayor.
STRINGS.MANDRAKEMAN_MANDRAKE_BATTLECRY[1] = "¡CRIMINAL!"
STRINGS.MANDRAKEMAN_MANDRAKE_BATTLECRY[2] = "¡ASALTANTE!"

-- Pig mans. / Hombres cerdo.
STRINGS.PIG_TALK_FOLLOWWILSON[1] = "TÚ AMABLE"
STRINGS.PIG_TALK_FOLLOWWILSON[2] = "YO AMARTE"
STRINGS.PIG_TALK_FOLLOWWILSON[3] = "TÚ BIEN"
STRINGS.PIG_TALK_LOOKATWILSON[3] = "FEA COSA NO CERDO"

-- Bunnymans. / Hombres conejo.
STRINGS.RABBIT_MEAT_BATTLECRY[2] = "¡REPUGNANTE!"
STRINGS.RABBIT_MEAT_BATTLECRY[3] = "¡HOMICIDA!"

-- Sunken boat. / Barca hundida. (Wolly)
STRINGS.SUNKEN_BOAT_REFUSE_TRADE[4] = "¡Grumete de agua dulce!"

-- Pirate parrot. / Loro pirata.
STRINGS.TALKINGBIRD.on_ground[3] = "¡Cabeza hueca!"
STRINGS.TALKINGBIRD.on_mounted[3] = "¿Sabes lo que haces?"

AddSimPostInit(function(player)
  if player.prefab == "wilbur" then
    STRINGS.BORE_TALK_LOOKATWILSON[3] = "FEO MONO NO SALVAJE"
    STRINGS.PIG_TALK_LOOKATWILSON[3] = "FEO MONO NO SALVAJE"
  end
end)
